name: CI
on: pull_request
jobs:
  test:
    name: Test -- tox
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.5'
        env:
          PIP_CERT: /etc/ssl/certs/ca-certificates.crt
      - name: Python pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
      - name: Run tests
        run: |
          pip install $(grep "^tox==" requirements/local.txt)
          tox
